### ISSUE TITLE
[Graphics] Set up player animation graph

### ISSUE THREAD

**Issue by Plutzz** [Plutzz/EscarGO#22]
Using blank animation clips, set up the player animation graph with the following animations

- [x] Walking
- [x] Sprinting
- [x] Idle
- [x] Minigame (This one is going to be the default animation for when the player is in a minigame

**Comment by p-vinh** [comment]
![Image](https://github.com/Plutzz/EscarGO/assets/85326677/848297bf-7c06-4e92-9dbf-dc8b75e0332e)

This is the current animation graph. Note that the dancing will be the "sprint"
