### ISSUE TITLE
[Gameplay] Player Controller

### ISSUE THREAD

**Issue by Plutzz** [Plutzz/EscarGO#4]
- [x] First Person Controller
  - [x] Velocity
  - [x] Sprint (with Stamina)
  - [x] Hold item/dish

- [ ]  Top Down Controller

**Comment by p-vinh** [comment]
Will Cooking/Interacting be its own state or should it be handled by the General State Machine?

**Comment by Plutzz** [comment]
> Will Cooking/Interacting be its own state or should it be handled by the General State Machine

Cooking/Interacting with food stations should be its own state
we are going to relinquish the player's input in this state

**Comment by Plutzz** [comment]
> * [x]  First Person Controller
>   
>   * [x]  Velocity
>   * [x]  Sprint (with Stamina)
>   * [x]  Hold item/dish
> * [ ]   Top Down Controller

Very good but there's two things I would like to change

- Airborne state feels sort of strange with no control at all
- If you rotate the top down camera to be more vertical, it changes the walking speed of the player
